CREATE TABLE "waiting_list" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"email" text NOT NULL,
	"first_name" text,
	"last_name" text,
	"company" text,
	"job_title" text,
	"industry" text,
	"company_size" text,
	"interests" text[],
	"referral_source" text,
	"expected_usage" text,
	"budget" text,
	"timeline" text,
	"additional_info" text,
	"status" text DEFAULT 'waiting' NOT NULL,
	"priority" integer DEFAULT 0 NOT NULL,
	"invited_at" timestamp,
	"registered_at" timestamp,
	"ip_address" text,
	"user_agent" text,
	"utm_source" text,
	"utm_medium" text,
	"utm_campaign" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "waiting_list_email_unique" UNIQUE("email")
);
